%% 
% This function uses timingSync.mat generated by getExpTime.m
%
function outputs = convertToSamples(inputTimes)

    load('./Utilities/timingSync.mat');     
       
    outputs = round((inputTimes - tOffset).*(rawRate + rateError));