function prog4HTeven() 

global ardVar;

panelConstants;

ZEROLOC = 12;

AXW = 15;
AXO = 16;
AYW = 17; 
AYO = 18; 
BXW = 19;
BXO = 20;
BYW = 21; 
BYO = 22; 
CXW = 23;
CXO = 24;
CYW = 25; 
CYO = 26; 
DXW = 27;
DXO = 28;
DYW = 29; 
DYO = 30; 



 


init = [SETGSBITS,3,0,0,0; ...
        CLEARBUFF,0,0,0,0; ...
        CLEARMEM, 1, 1, 0, 0; ...
        SETDATA, ZEROLOC, 0, 0, 0; ...  
        SETDATA, X2, 24, 0, 0; ...
        SETDATA, Y2, 32, 0, 0; ...
        SETDATA, BXW, 4,0,0;...
        SETDATA, BXO, 10,0,0;...
        SETDATA, BYW, 14,0,0;...
        SETDATA, BYO, 12,0,0;...       
        SETDATA, ONVAL, 0, 0, 0; ...
        SETDATA, OFFVAL, 2, 0, 0];

prog = [C1ICLEARBUFF,...
        RADD, BXW, ZEROLOC, X1, 0, ...
        RADD, BXO, X0, X3, 0, ...
        RADD, BYW, ZEROLOC, Y1, 0, ...
        RADD, BYO, ZEROLOC, Y3, 0, ...
        C1BOXARRAY, ...
        C1FLIPBUFF,C1ENDPROG,ENDPROG];
        
        
        
        












% zeroR = 12;
% twoR  = 13;
% widthR = 14;
% lengthR = 15;
% heightR = 17;
% maxXR = 18;
% stemR = 19;
% stemRdiv2 = 20;
% halfCycleR = 21;
% quartCycleR = 22;
% X0halfR = 23;
% X0advR = 24;
% 
%            init  = [SETGSBITS,1,0,0,0; ...
%                     CLEARBUFF,0,0,0,0; ...
%                     CLEARMEM, 1, 1, 0, 0; ...
%                     SETDATA, zeroR, 0, 0, 0; ...
%                     SETDATA, twoR, 2, 0, 0; ...
%                     SETDATA, widthR, width, 0, 0; ...
%                     SETDATA, lengthR, length, 0, 0; ...
%                     SETDATA, heightR, height, 0, 0; ...
%                     SETDATA, maxXR, ardVar.MaxX, 0, 0; ...
%                     SETDATA, ONVAL, 0, 0, 0; ...
%                     SETDATA, OFFVAL, 1, 0, 0];
% ZZ = 36;                
% AA = 73;
% BB = 88;
% CC = 125;
% DD = 162;
% EE = DD + 15;
% FF = EE + 37;
% 
%                 
% prog = [C1ICLEARBUFF,...
%         RSUBT, lengthR, widthR, stemR, 0, ...   % Setup registers
%         RDIV, stemR, twoR, stemRdiv2, 0, ...
%         RDIV, maxXR, twoR, halfCycleR, 0, ...
%         RDIV, halfCycleR, twoR, quartCycleR, 0, ...
%         RADD, stemRdiv2, X0, X0advR,0, ...      % Advance the phase for stems
%         JUMPIF, maxXR, X0advR, ZZ, 0, ...
%         SUBT, X0advR, ardVar.MaxX, 0, 0, ...
%         RADD, zeroR, X0advR, X1, 0, ...         % Plot stem1, ZZ
%         RADD, widthR, X1, X2, 0, ...
%         RADD, zeroR, heightR, Y1, 0, ...
%         RADD, lengthR, Y1, Y2, 0, ...
%         C1IBOX, ...  
%         JUMPIF, maxXR, X2, AA, 0, ...           % Finish stem 1 if cycle wrap
%         SUBT, X2, ardVar.MaxX, 0, 0, ...
%         RADD, zeroR, zeroR, X1, 0, ...
%         C1IBOX, ...       
%         RADD, X0advR, halfCycleR, X0halfR, 0, ...   % Add a halfCycle to X0, AA
%         JUMPIF, maxXR, X0halfR, BB, 0, ...
%         SUBT, X0halfR, ardVar.MaxX, 0, 0, ... 
%         RADD, zeroR, X0halfR, X1, 0, ...    % BB
%         RADD, widthR, X1, X2, 0, ...
%         RADD, zeroR, heightR, Y1, 0, ...
%         RADD, lengthR, Y1, Y2, 0, ...
%         C1IBOX, ...
%         JUMPIF, maxXR, X2, CC, 0, ...
%         RADD, zeroR, zeroR, X1, 0, ...
%         SUBT, X2, ardVar.MaxX, 0, 0, ...
%         C1IBOX, ...
%         RADD, zeroR, X0, X1, 0, ...             % Plot bottom bar
%         RADD, X1, lengthR, X2, 0, ...
%         RADD, zeroR, heightR, Y1, 0, ...
%         RADD, Y1, widthR, Y2, 0, ...
%         C1IBOX, ...
%         JUMPIF, maxXR, X2, DD, 0, ...           
%         SUBT, X2, ardVar.MaxX, 0, 0, ...
%         RADD, zeroR, zeroR, X1, 0, ...
%         C1IBOX, ... 
%         RADD, halfCycleR, X0, X0halfR, 0, ...   % Plot top bar
%         JUMPIF, maxXR, X0halfR, EE, 0, ...
%         SUBT, X0halfR, ardVar.MaxX, 0, 0, ...        
%         RADD, zeroR, X0halfR, X1, 0, ...         
%         RADD, X1, lengthR, X2, 0, ...
%         RADD, stemR, heightR, Y1, 0, ...
%         RADD, Y1, widthR, Y2, 0, ...
%         C1IBOX, ...
%         JUMPIF, maxXR, X2, FF, 0, ...           
%         SUBT, X2, ardVar.MaxX, 0, 0, ...
%         RADD, zeroR, zeroR, X1, 0, ...
%         C1IBOX, ...         
%         C1FLIPBUFF,...                          
%         C1ENDPROG, ...
%         ENDPROG];

    
    



ardDispOff();
for i=1:size(init,1)
    ardI2Cecho(init(i,1),init(i,2),init(i,3),init(i,4),init(i,5));
end    
for i=1:size(prog,2)
    ardI2Cecho(SETPROG, i-1, prog(i), 0, 0);
end