function progDiscPatterns()

width = 3;
length = 11;
height = 8;

global ardVar;

panelConstants;

ZEROLOC = 12;
AXW = 13;
AXO = 14;
AYW = 15;
AYO = 16;
BXW = 17;
BXO = 18;
BYW = 19;
BYO = 20;
CXW = 21;
CXO = 22;
CYW = 23;
CYO = 24;



init = [SETGSBITS,3,0,0,0; ...
        CLEARBUFF,0,0,0,0; ...
        CLEARMEM, 1, 1, 0, 0; ...
        SETDATA, ZEROLOC, 0, 0, 0; ...
        SETDATA, AXW, 18, 0, 0; ... 
        SETDATA, AXO, 3, 0, 0; ...
        SETDATA, AYW, 4, 0, 0; ...
        SETDATA, AYO, 27, 0, 0; ...
        SETDATA, BXW, 4, 0, 0; ...
        SETDATA, BXO, 10, 0, 0; ...
        SETDATA, BYW, 12, 0, 0; ...
        SETDATA, BYO, 18, 0, 0; ...
        SETDATA, CXW, 10, 0, 0; ...
        SETDATA, CXO, 7, 0, 0; ...
        SETDATA, CYW, 5, 0, 0; ...
        SETDATA, CYO, 11, 0, 0; ...
        SETDATA, Y2, 32, 0, 0; ...
        SETDATA, X2, 48, 0, 0; ...
        SETDATA, ONVAL, 0, 0, 0; ...
        SETDATA, OFFVAL, 1, 0, 0];

prog = [C1ICLEARBUFF,...
        RADD, AXW, ZEROLOC, X1, 0, ...
        RADD, AXO, X0, X3, 0, ...
        RADD, AYW, ZEROLOC, Y1, 0, ...
        RADD, AYO, ZEROLOC, Y3, 0, ...
        C1BOXARRAY, ...
        RADD, BXW, ZEROLOC, X1, 0, ...
        RADD, BXO, X0, X3, 0, ...
        RADD, BYW, ZEROLOC, Y1, 0, ...
        RADD, BYO, ZEROLOC, Y3, 0, ...
        C1BOXARRAY, ...
        RADD, CXW, ZEROLOC, X1, 0, ...
        RADD, CXO, X0, X3, 0, ...
        ADD, X3, 24, 0, 0, ...
        RADD, CYW, ZEROLOC, Y1, 0, ...
        RADD, CYO, ZEROLOC, Y3, 0, ...
        C1BOXARRAY, ...
        C1FLIPBUFF,C1ENDPROG,ENDPROG];


  

ardDispOff();
for i=1:size(init,1)
    ardI2Cecho(init(i,1),init(i,2),init(i,3),init(i,4),init(i,5));
end    
for i=1:size(prog,2)
    ardI2Cecho(SETPROG, i-1, prog(i), 0, 0);
end