function analyzeManySOLO()

baseCode = '110118-';

odorList = {...
        'EV',...
        'H2O',...
        'PO',...
        '8AC-2',...
        'ACV-1',...
        'ACV-2',...
        'ACV-4',...
        'ACV-6',...
        'MeS-2',...
        'Benz-3',...
        'Butyric-2',...
        '3MT1P-2',...
        'ETA-9',...
        'Phenyl-2',...
        'GerAc-2',...
        'EtOH-2'
};

for odorN = 1:size(odorList,2)
    experiment = [baseCode, odorList{odorN}];
    
    analyzeSOLO(experiment); close all;
end

disp('Done Analyzing');